[package]
name = "roccat-tools"
version = "0.1.0"
authors = ["Ash Levy <ashlea@protonmail.com>"]

[workspace]
members = ["libroccat"]

[dependencies]
libroccat = { path = "libroccat" }
clap = "2.27.1"
dyon = "0.25.0"
error-chain = "0.11.0"
