[package]
name = "libroccat"
version = "0.1.0"
authors = ["Ash Levy <ashlea@protonmail.com>"]

[dependencies]
bitfield = { path = "../bitfield" }
hidraw-derive = { path = "hidraw-derive" }
failure = "0.1.1"
futures = "0.1.17"
libudev = "0.2.0"
log = "0.3.9"
nix = "0.9.0"
