[package]
name = "libroccat"
version = "0.1.0"
authors = ["Ash Levy <ashlea@protonmail.com>"]

[dependencies]
bitfield = { path = "../bitfield" }
hidraw-derive = { path = "hidraw-derive" }
error-chain = "0.11.0"
futures = "0.1.17"
libudev = "0.2.0"
nix = "0.9.0"
