[package]
authors = ["Ash Levy <ashlea@protonmail.com>", "panicbit <panicbit.dev@gmail.com>"]
name = "hidraw-derive"
version = "0.1.0"

[dependencies]
quote = "0.4.2"
syn = "0.12.10"

[lib]
proc-macro = true
